Slate says hi
IPLSplatoon/Radia pull request #4
Opened 2021-03-31 00:57 UTC by kjhf

- Moved get_presence_message to separate file
- Compatibility for no Google connector / local running without setup
- invalid_whatis choices -- remove empty response...
- Added Server cog and clear_checkin command

2021-05-12 18:55 UTC, LeptoFlare approved these changes
im late but looks good

WAIT IVE BEEN PUSHING TO YOUR BRANCH BY ACCIDENT THIS ENTIRE TIME

2021-05-20 17:11 UTC, vlee489 requested changes
Mostly looks good, but a few changes are needed

2021-05-20 17:11 UTC, vlee489 commented on radia/cogs/info.py
>      def invalid_whatis(self, prefix):
Please can we not have these random messages if an invalid `whatis` is asked for, and just say it does not exist please, these are frankly ridiculous.

2021-05-20 17:11 UTC, vlee489 commented on radia/cogs/info.py
>      def invalid_whatis(self, prefix):
if not ridiculous, some of them are rude

2021-05-20 17:11 UTC, vlee489 commented on radia/__main__.py
> +bot = Bot(command_prefix="^", intents=intents)
This `bot = Bot(command_prefix="^", intents=intents)` does not look correct, should be 

```python
command_prefix="!" if not os.getenv("DEBUG") else "^"
```

2021-05-20 17:12 UTC, vlee489 commented on radia/cogs/info.py
>      def invalid_whatis(self, prefix):
If you want to keep these somewhere are an internal joke, put them into [Sheetbot](https://github.com/IPLSplatoon/SheetBot)

2021-05-20 17:13 UTC, vlee489 commented on radia/__main__.py
> +bot = Bot(command_prefix="^", intents=intents)
Fixed issue in Merge Conflict

2021-05-23 02:39 UTC, LeptoFlare commented on radia/cogs/info.py
>      def invalid_whatis(self, prefix):
Resolved, see https://github.com/IPLSplatoon/Radia/pull/4/commits/0f5665aa2765644172a171b81938326530b1f673

The inside jokes only show up if the command is invoked inside of the IPL Staff server.
Additionally, I request that Radia be added to the IPL Staff server so you do not need to update sheetbot's code every time I add more inside jokes.

2021-05-23 23:21 UTC, vlee489 approved these changes

2021-05-23 23:24 UTC, merged